name: lab-testing

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'tests/unit/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'tests/e2e/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run unit tests
        run: poetry run pytest tests/unit

  e2e-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run end-to-end tests
        run: poetry run pytest tests/e2e


